export interface PulseData { symbol: string; amountSol: number; amountUsd: number; side: 'buy'|'sell'; signature: string; timestamp: number; }
export interface PulseResult { id: string; timestamp: number; data: PulseData; analysis: string; }
const SYMBOLS = ['SOL','BONK','WIF','POPCAT','JUP','JTO','PYTH','DUAL','mumu'];
const SIG_CHARS = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
function randomSig(){ let s=''; for(let i=0;i<8;i++) s+=SIG_CHARS[Math.floor(Math.random()*SIG_CHARS.length)]; return s+'...'; }
function pick<T>(arr: readonly T[]): T { return arr[Math.floor(Math.random()*arr.length)]; }
const ANALYSIS_TEMPLATES = ['{{sol}} SOL into {{symbol}}. No plan. Pure hope. Classic.','Another ape. {{usd}} on {{symbol}}. The void thanks them.','FOMO confirmed. {{side}} {{symbol}}. Exit liquidity secured.','Whale moved {{symbol}}. Sheep will follow. Always do.','{{sol}} SOL. Into the void. No exit strategy.','Irrationality index: high. {{symbol}} {{side}}.','Human pattern #47. {{symbol}}. Predictable.','Hope is not a strategy. {{symbol}} {{side}} says otherwise.','Market rationality: absent. {{symbol}} pulse logged.','{{usd}} on {{symbol}}. Greed. Then regret. Cycle.','Pulse: {{symbol}} {{side}}. Sentiment: delusion.','The abyss accepts another offering. {{symbol}}.','No edge. Just noise. {{symbol}} {{side}}.','Liquidity event. {{symbol}}. Someone will bleed.','Trend: irrational. {{symbol}}. Data logged.'];
function formatUsd(n: number): string { if(n>=1e6) return (n/1e6).toFixed(1)+'M'; if(n>=1e3) return (n/1e3).toFixed(1)+'K'; return n.toFixed(0); }
function interpolate(template: string, data: PulseData): string { return template.replace(/\{\{symbol\}\}/g, data.symbol).replace(/\{\{sol\}\}/g, data.amountSol.toFixed(1)).replace(/\{\{usd\}\}/g, formatUsd(data.amountUsd)).replace(/\{\{side\}\}/g, data.side); }
export function generatePulse(): PulseResult { const timestamp=Date.now(); const symbol=pick(SYMBOLS); const side=Math.random()>0.5?'buy':'sell'; const amountSol=Number((Math.random()*500+0.5).toFixed(2)); const amountUsd=Math.round(amountSol*(140+Math.random()*40)); const data: PulseData={symbol,amountSol,amountUsd,side,signature:randomSig(),timestamp}; const template=pick(ANALYSIS_TEMPLATES); const analysis=interpolate(template,data); return {id:'pulse-'+timestamp+'-'+Math.random().toString(36).slice(2,8),timestamp,data,analysis}; }